### ISSUE TITLE
Need to add tests for sendBeacon

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/beacon#29] opened 2016-04-21 17:51 UTC

**Comment by toddreifsteck** [comment] 2016-05-12 05:18
One of our devs is locking down and cleaning up some tests for sendBeacon. I expect I'll be able to submit the client portion of this by end of May. It will likely take a bit of work by @plehegar at that point to get the server portion of the code wired up as internal framework is ASP.Net.

**Comment by toddreifsteck** [comment] 2016-10-19 18:09
https://github.com/w3c/web-platform-tests/pull/4024

**Comment by igrigorik** [comment] 2016-10-24 22:16
@toddreifsteck awesome, thanks Todd! Took a pass over the tests, and left some questions and comments on the PR: https://github.com/w3c/web-platform-tests/pull/4024#pullrequestreview-5544472

Points we need to address: 

1. We did not spec a hard limit on max size of payload. I'm not sure if/how we want to test that.

 Related.. Chrome fails a subset of the submitted tests due to how it implements max size. Specifically, unlike Edge/FF we currently set a 64KB overall quota across for the lifetime of the context; each time a beacon is sent, we decrement its size from the quota and eventually drain the full quota in the tests and hence fail delivery of "max payload" tests... Technically, I do believe that this behavior is acceptable within current spec language. In practice, however, I think it's a bit restrictive and we might want to relax it... That said, as an interesting data point, so far this has not come up as a reported user problem, and it does serve to demonstrate that different UAs can adopt different strategies -- as intended. 

2. As noted in https://github.com/w3c/web-platform-tests/pull/4024#discussion_r84792665, we have three different implementations throwing three different errors on invalid URL. We need to sort out how we want to handle that.

3. Neither FF nor Chrome current expose sendBeacon on Worker: https://github.com/w3c/beacon/issues/37

**Comment by igrigorik** [comment] 2016-12-21 16:34
(3) was resolved in https://github.com/w3c/beacon/issues/37.
(2) was addressed in https://github.com/w3c/web-platform-tests/pull/4024#discussion_r84792665.
(1) we're working on in https://github.com/w3c/beacon/issues/38.

Closing this, let's continue in (1).. which will also define the test update(s).

**Closed by igrigorik** 2016-12-21 16:34 UTC
